on:
  push:

name: CI

jobs:

  jsonlint:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y python3-demjson
      - uses: actions/checkout@v1
      - run: jsonlint --strict ./directory.json
